// <auto-generated />
using System;
using CurrencyApp.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyApp.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CurrencyApp.Entity.Models.Currency", b =>
                {
                    b.Property<int>("InternalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CharCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrencyDataId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Nominal")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NumCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Previous")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("InternalId");

                    b.HasIndex("CurrencyDataId");

                    b.ToTable("Currencies");
                });

            modelBuilder.Entity("CurrencyApp.Entity.Models.CurrencyData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("CurrencyData");
                });

            modelBuilder.Entity("CurrencyApp.Entity.Models.Currency", b =>
                {
                    b.HasOne("CurrencyApp.Entity.Models.CurrencyData", "CurrencyData")
                        .WithMany("Currencies")
                        .HasForeignKey("CurrencyDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyData");
                });

            modelBuilder.Entity("CurrencyApp.Entity.Models.CurrencyData", b =>
                {
                    b.Navigation("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
